plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/nelsonchan/Downloads/LAUNCH-READY-TEMPLATE copy 3/router-files"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/baby-blue/*"
to = "https://burgundyset.netlify.app/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/baby-blue"
to = "https://burgundyset.netlify.app/"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "https://burgundyset.netlify.app/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]